// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAXZEmsy0QrNfOJNl8NGXkZTh9tmn_sl8',
    appId: '1:579814252308:android:fcd24bea5bd3a1c2286c01',
    messagingSenderId: '579814252308',
    projectId: 'craftnect-658c7',
    storageBucket: 'craftnect-658c7.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmzDmTW1JCAf1u6ZZzNQP116IpmSX8nwU',
    appId: '1:579814252308:web:1cfffb7c91f12184286c01',
    messagingSenderId: '579814252308',
    projectId: 'craftnect-658c7',
    authDomain: 'craftnect-658c7.firebaseapp.com',
    storageBucket: 'craftnect-658c7.firebasestorage.app',
    measurementId: 'G-ZQJWW7ZKS6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmzDmTW1JCAf1u6ZZzNQP116IpmSX8nwU',
    appId: '1:579814252308:web:6bca9ed7be3076ff286c01',
    messagingSenderId: '579814252308',
    projectId: 'craftnect-658c7',
    authDomain: 'craftnect-658c7.firebaseapp.com',
    storageBucket: 'craftnect-658c7.firebasestorage.app',
    measurementId: 'G-8JV9WYKN0B',
  );

}